---
title: "index"
author: "Luluu Chen"
date: '2022-08-13'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction 

Racism exists across the United States, with people of color being treated differently than Whites. The jail system in the United States is where racism is most visible, particularly over-policing of people of color, which has resulted in disproportionately imprisonment of people of color. As a result, I wish to examine incarceration using a dataset to determine whether or not individuals of color face disproportionate incarceration. 
Using incarceration collected by the Vera Institute, the variables I have chosen to are: year, county name, states, total jail population, black jail population, and white jail population. I have chosen to focus on the differing impacts of incarcerations on both the White and Black races respectively.


## Paragraph of Summary

### Total black jail population between the year of 2015 to 2018

Comparing the total white jail population state such as New York has higher black in jail population. As in the other hand how state like Washington and Oregon having more population of white in jail

### Total white jail population between the year of 2015 and 2018

Tennessee has one of the highest white jail population of 71302 total together from year 2015 to 2018

### Ratio of total population between the aged 15-64 for each race every year after 2015 to 2018 

When I compared the ratios of each race to the overall population, I discovered that the year with the highest Black population ratio was 13.48% in the year of 2018

### State that has the highest population in jail in the year of 2018 

Within the selected states I have found that Tennesse has the highest jail population in the year of 2018 total of black and white race

### State that has the least jail population in the year of 2016

Within the selected states I have found that Wyomings has the least jail population in the year of 2016 total with of black and white race

## Trends Over Time Chart

The trends over time chart that I did was an bar chart in which it's showing the total number of people that was in jail within the selected states which are; NY, WA, OR, TN, and WY between the year of 2015 to 2018. By looking at the chart, I can clearly see how Tennesse has the overall highest jail population between 2015 to 2018. Also, by looking at the chart you can see how Washington State are increasing little each year from 2015 to 2018 and at the year of 2018 Washington has a total population in jail of 12,765

## Comparison Chart 

The comparison chart that I did was an stack bar chart in which it's showing an comparison between two race white and black. In the chart, it's showing the total number of black and white in jail from 2015 to 2018 in selected states which are also NY, WA, OR, TN, adn WY. By looking at the chart between the two races you can clearly see how in the year 2015 to 2018 Tennessee has the highest White jail population and compare to New York where it has the highest Black jail population.

## Map

The map that I did was an US map showing the population of Black in jail in the selected states in the US. In the map, you can see how CA, TX, AL, PA, ect are color for their black population within each state. On the side of the map it has a scale of the population from 0 to 5000 and how looking at the map CA has one of the highest comparing to the other selected states.